spring:
  pulsar:
    client:
      service-url: pulsar://10.42.53.213:6650
  state:
    r2dbc:
      url: r2dbc:postgresql://localhost/accounts_state_database
      password: 12345
      username: postgres
  event:
    r2dbc:
      url: r2dbc:postgresql://localhost/accounts_event_database
      password: 12345
      username: postgres

  jpa:
    show-sql: true